name: Build Tasmota ESP32-C3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio wheel
          pip install littlefs-python



      - name: Build Firmware
        run: |
          cat > platformio_override.ini << 'EOF'
[platformio]
default_envs = tasmota32c3-custom

[env:tasmota32c3-custom]
extends = env:tasmota32c3
build_flags = 
    ${env:tasmota32c3.build_flags}
    -DUSE_CONFIG_OVERRIDE
    -DUSE_CSE7766
    -DUSE_ENERGY_SENSOR
EOF
          
          pio run -t clean -e tasmota32c3-custom
          pio run -e tasmota32c3-custom
          

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: tasmota32c3-firmware
          path: .pio/build/tasmota32c3/*.bin
