;[platformio]
;default_envs = tasmota32c3-custom

;[env:tasmota32c3-custom]
;extends = env:tasmota32c3
;build_flags = 
;    ${env:tasmota32c3.build_flags}
;    -DUSE_CONFIG_OVERRIDE
;    -DUSE_CSE7766
;    -DUSE_ENERGY_SENSOR



; 强制只编译ESP8266红外固件，删除所有ESP32/32C3等编译目标
[platformio]
default_envs = tasmota-ir

; ESP8266核心编译配置（固定不变）
[env:tasmota-ir]
extends = env:tasmota
board = esp01_4m  ; 适配ESP8266通用版（1M Flash），如果是4M Flash改esp8266_4m
build_flags = ${env:tasmota.build_flags} -DMODULE_IR=1
lib_deps = ${env:tasmota.lib_deps}
