#ifndef _USER_CONFIG_OVERRIDE_H_
#define _USER_CONFIG_OVERRIDE_H_

#define USE_IR_REMOTE
#define USE_IR_RECEIVE

#undef DEFAULT_TEMPLATE
#define DEFAULT_TEMPLATE "{\"NAME\":\"Lerlink_ESP8266_IR\",\"GPIO\":[32,0,0,0,1056,1088,0,0,0,576,0,0,0,0],\"FLAG\":0,\"BASE\":1}"

#undef MODULE
#define MODULE 0

#undef TEMPLATE_AUTODETECT
#define TEMPLATE_AUTODETECT 0

#undef CFG_HOLDER
#define CFG_HOLDER 999889

#endif
