name: Tasmota_build_devel

on:
  workflow_dispatch:

jobs:
  build_esp8266_ir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install PlatformIO
        run: |
          pip install -U platformio
          # 关键：复制覆盖配置文件，确保板型定义生效
          cp ./platformio_override_sample.ini ./platformio_override.ini

      - name: Build ESP8266 IR
        run: platformio run -e tasmota-ir

      - uses: actions/upload-artifact@v4
        with:
          name: firmwares
          path: .pio/build/tasmota-ir/
